### ISSUE TITLE
Can't connect to database

### ISSUE THREAD

**Issue by sb56637** [kasperisager/vanilla-dockerized#3]
Hi there, whatever I try it seems that it can't connect to the database. It just gives me a "ValidateConnection" red error. Any suggestions on how to debug this? Thanks a lot!

**Comment by kasperisager** [comment]
What are you inputting as the database URL?

**Comment by sb56637** [comment]
I've tried localhost, 127.0.0.1, and the VM's public IP.

**Comment by kasperisager** [comment]
That'd be why; you'll have to use the name assigned to the link in the Compose configuration: https://github.com/kasperisager/vanilla-dockerized/blob/0ae290a3b0e422cf0b3ed09869ccc6b40ad7279c/docker-compose.yml#L15

It would be `database` in this case.

**Comment by sb56637** [comment]
Ah, sure enough, that did the trick. And what would happen if I wanted to use an external database server? Would I change the `127.0.0.1:3306:3306` line in the Compose configuration?

**Comment by kasperisager** [comment]
If you want to use an external database, simply input the corresponding address when installing Vanilla and disregard the included Percona container.
