### ISSUE TITLE
Upgrade problem

### ISSUE THREAD

**Issue by sb56637** [kasperisager/vanilla-dockerized#4]
Hi, when I created my first Vanilla installation in Docker, I forgot to change the slightly old  `2.1.11` version in the /front/Dockerfile. Later I followed the upgrade instructions of 

> update the VANILLA_VERSION environment variable in front/Dockerfile and then run:
> 
> docker-compose build front
> docker-compose up

I used `2.2rc1` for the version. But after rebuilding, it gave me an error:

`docker-compose up`
`Recreating vanilla_cache_1...`
`Recreating vanilla_database_1...`
`Duplicate volume "/var/vanilla/database/data": "/var/lib/mysql" already in use, mounted from "/var/vanilla/database/data"`

It also still showed the old 2.1.11 version number in the bottom right corner of the forum.

Thanks!

**Comment by kasperisager** [comment]
You might be running an older version of Compose; non-changed containers shouldn't be rebuilt when running `docker-compose up`.

**Comment by sb56637** [comment]
Ah, I see. Could be, Ubuntu 15.10 has a surprisingly old version, 1.3.1 from June 21 2015. I'll report back if this happens again on a newer compose version. Appreciate the help!

**Comment by kasperisager** [comment]
No problem, holler if it works out!

**Comment by sb56637** [comment]
Ok, sweet, I upgrade to the latest RC of docker-compose and also upgraded to the official Docker repo version of Docker, and an upgrade worked fine. Thanks for pointing me in the right direction!
