### ISSUE TITLE
Clean URLs don't work on Vanilla 2.2 RC1

### ISSUE THREAD

**Issue by geckolinux** [kasperisager/vanilla-dockerized#6]
Hi, I tried a vanilla-dockerized installation of Vanilla 2.2 RC1, and clean URLs don't work. They *do* work correctly out of the box on Vanilla 2.1.12p3 in vanilla-dockerized. But with Vanilla 2.2 RC1 it has dirty URLs and I can't find a way to enable clean URLs. I'm not sure if it's a 2.2rc1 bug, or possible an incompatibility with some new URL scheme of 2.2rc1 with the nginx rewrite rules?

**Comment by kasperisager** [comment]
Closing as I haven't been able to replicate this on 2.2 final.
