### ISSUE TITLE
Instructions on disabling cache & extending

### ISSUE THREAD

**Issue by SevereOverfl0w** [kasperisager/vanilla-dockerized#7]
Absolutely love this project, you may be the first person I've seen doing docker correctly.

I thought you may want to include some instructions on disabling the cache (simple enough) and maybe instructions on how to extend the docker-compose file to be part of another, although that's a less-common case.

**Comment by kasperisager** [comment]
Thrilled to hear that you like the project!

I however won't be providing and maintaining any additional documentation on how to customise the Vanilla config or any Docker-specific aspects. This should instead be found in the respective documentation for the two.
